---
version: '3.9'
services:
  web:
    build: .
    ports: [80:80]
    volumes: [./default.conf:/etc/nginx/conf.d/default.conf]
    environment:
      - SERVER_NAME=${SERVER_NAME:-pcdm-staging.lib.princeton.edu}  # Default value if no env variable is set
